
const allProducts = {

    generalBook: {
      type : "کتاب عمومی" ,
      products: [
        {
          id: 1,
          category: "general-book",
          title: "عشق در گذر زمستانی (جیبی)(لوکس)",
          price: "108500",
          cover: "./pictures/book-1.jpg",
          discount: 30,
          publisher: "پاریس",
          author : "آن مایکلز" , 
          translator : "نیلوفر دهقانی"
        },
        {
          id: 2,
          category: "general-book",
          title: "رشد بدن دختران در دوره بلوغ ",
          price: "15000",
          cover: "./pictures/book-2.jpg",
          discount: 30,
          publisher: "صابرین",
          author : " والری لی شیفر " , 
          translator : " محمدعلی شیخ "
        },
        {
          id: 3,
          category: "general-book",
          title: "اتو دوست مهربانی (خشتی)(نشر فرهنگ اسلامی)",
          price: "312000",
          cover: "./pictures/book-3.jpg",
          discount: 35,
          publisher: "نشر دفتر فرهنگ اسلامی",
          author : " فروغ علی شاهرودی" , 
          translator : ""
        },
        {
          id: 4,
          category: "general-book",
          title: "دیوان حافظ همراه با فال (وزیری)(قابدار)(چرم لیزری)",
          price: "656000",
          cover: "./pictures/book-4.jpg",
          discount: 30,
          publisher: "پارمیس",
          author : " خواجه شمس‌الدین محمد حافظ شیرازی" , 
          translator : ""
        },
        {
          id: 5,
          category: "general-book",
          title: "زیر سر کوه ",
          price: "312000",
          cover: "./pictures/book-5.jpg",
          discount: 40,
          publisher: "نشر شهرستان ادب",
          author : " فاطمه هاوشکی" , 
          translator : ""
        },
        {
          id: 6,
          category: "general-book",
          title: "دروس طلایی 10 دهم تجربی چاپ 1401 ",
          price: "312000",
          cover: "./pictures/book-6.jpg",
          discount: 30,
          publisher: "گاج",
          author : " علی ضیانی " , 
          translator : ""
        },
        {
          id: 7,
          category: "general-book",
          title: "مشاوره نوجوانان ",
          price: "312000",
          cover: "./pictures/book-7.jpg",
          discount: 30,
          publisher: "نگاه معاصر",
          author : " کاترین گلدارد" , 
          translator : " سحر شمس"
        },
        {
          id: 8,
          category: "general-book",
          title: "از هم ریخته ",
          price: "312000",
          cover: "./pictures/book-8.jpg",
          discount: 35,
          publisher: "ایهام",
          author : " داوود جمالی" , 
          translator : ""
        },
        {
          id: 9,
          category: "general-book",
          title: "جنایت و مکافات ",
          price: "325000",
          cover: "./pictures/book-9.jpg",
          discount: 38,
          publisher: "نشر آوای مهدیس",
          author : "فئودور داستایوفسکی " , 
          translator : " منیره کفتری"
        },
        {
          id: 10,
          category: "general-book",
          title: "تفکراتی درباره زندگی ",
          price: "108500",
          cover: "./pictures/book-10.jpg",
          discount: 40,
          publisher: "سرایش",
          author : " الکسی کارل" , 
          translator : " علیرضا جاویدانی"
        },
        {
          id: 11,
          category: "general-book",
          title: "شبهای روشن (جیبی)",
          price: "70000",
          cover: "./pictures/product-11.jpg",
          discount: 10,
          publisher: "نشر ماهی",
          author : " فئودور داستایوفسکی" , 
          translator : " سروش حبیبی"
        },
        {
          id: 12,
          category: "general-book",
          title: "به امید دل بستم ",
          price: "225000",
          cover: "./pictures/product-12.jpg",
          discount: 10,
          publisher: "نوین",
          author : " لنکالی" , 
          translator : " پگاه فرهنگ مهر"
        },
        {
          id: 13,
          category: "general-book",
          title: "سفر به انتهای شب (شومیز)",
          price: "420000",
          cover: "./pictures/product-13.jpg",
          discount: 15,
          publisher: "نوین",
          author : " لویی فردینان سلین" , 
          translator : " فرهاد غبرایی"
        },
        {
          id: 14,
          category: "general-book",
          title: "نیک سرشت ",
          price: "249000",
          cover: "./pictures/product-14.jpg",
          discount: 10,
          publisher: "نشر میلکان",
          author : " بکی کندی" , 
          translator : " شقایق الکائی"
        },
        {
          id: 15,
          category: "general-book",
          title: "بخش دی ",
          price: "239000",
          cover: "./pictures/product-15.jpg",
          discount: 10,
          publisher: "نشر نون",
          author : " فریدا مک فادن" , 
          translator : " صبا ایمانی"
        },
        {
          id: 16,
          category: "general-book",
          title: "وقتی نیچه گریست (گالینگور)",
          price: "325000",
          cover: "./pictures/product-16.jpg",
          discount: 10,
          publisher: "نشر قطره",
          author : " اروین یالوم" , 
          translator : " سپیده حبیب"
        },
        {
          id: 17,
          category: "general-book",
          title: "می خواهم بمیرم ولی هوس دوکبوکی کرده ام ",
          price: "129000",
          cover: "./pictures/product-17.jpg",
          discount: 10,
          publisher: "نشر مون",
          author : " بک سهی " , 
          translator : " ندا بهرامی نژاد "
        },
        {
          id: 18,
          category: "general-book",
          title: "خصم ",
          price: "325000",
          cover: "./pictures/product-18.jpg",
          discount: 10,
          publisher: "نشر خانه هنر مد",
          author : "امانوئل کارر" , 
          translator : "ابوالفضل الله دادی"
        },
        {
          id: 19,
          category: "general-book",
          title: " مرشد و مارگاریتا (پالتویی)(گالینگور) ",
          price: "555000",
          cover: "./pictures/product-19.jpg",
          discount: 10,
          publisher: " نشر کتاب پارسه ",
          author : " میخائیل بولگاکف ", 
          translator : " حمیدرضا آتش برآب "
        },
        {
          id: 20,
          category: "general-book",
          title: " سمفونی مردگان  ",
          price: "242000",
          cover: "./pictures/product-20.jpg",
          discount: 10,
          publisher: " نشر ققنوس ",
          author : " عباس معروفی " , 
          translator : ""
        },
      ],
  
      categories: [
        "همه",
        " ادبیات - آموزش، نقد و نظریه ",
        "ادبیات - داستان کوتاه ایرانی ",
        "ادبیات - داستان کوتاه خارجی ",
        "ادبیات - رمان ایرانی ",
        "ادبیات - رمان خارجی ",
        "ادبیات - شعر خارجی ",
        "ادبیات - شعر کلاسیک",
        "ادبیات - شعر نو ",
        "ادبیات - متون کهن ",
        "ادبیات - نامه نگاری ",
        "اقتصادی - عمومی",
        "پزشکی و روان‌درمانی - زنان و زایمان",
        "تاریخ - اروپا",
        "تاریخ - اسطوره",
        "تاریخ - اسلام",
        "تاریخ - ایران",
        "حقوقی - عمومی",
        "روانشناسی - ازدواج و زناشویی ",
        " روانشناسی - ذهن و روح ",
        "روانشناسی - عمومی",
        "روانشناسی - موفقیت",
        "زندگی نامه و خاطره - زندگی نامه ، سرگذشتنامه ",
        "زندگی نامه و خاطره - سفرنامه",
        "سیاست - ارتباطات سیاسی",
        "سیاست - جنگ",
        "سیاست - جهانی شدن",
        " سیاست - مرجع ",
        "علمی - عمومی ",
        " علوم اجتماعی - انسان شناسی ",
        " علوم اجتماعی - جامعه شناسی و مردم شناسی ",
        "علوم اجتماعی - فرهنگ و ارتباطات فرهنگی ",
        "فلسفه - عمومی ",
        " فلسفه - نقد و نظریه ",
        "کسب و کار و تجارت - راه‌اندازی و توسعه‌ی کسب و کار ",
        "مذهبی - دعا ",
        "مذهبی - رساله و احکام",
        "مذهبی - عمومی ",
        "ورزشی - پرورش اندام",
        "ورزشی - یوگا ",
        "هنر - معماری ",
      ],
  
      publishers: [
        "همه",
        "آسیم",
        "اساطیر",
        "اطلاعات",
        "افکار",
        "بامداد کتاب",
        "بهار سبز",
        "پرسمان",
        "پیام عدالت",
        "ثالث",
        "جوینده",
        "جیحون",
        "دنیای کتاب",
        "دیدار",
        "روزبهان",
        "زرین و سیمین",
        "ساحل",
        "سخن",
        "سوره مهر",
        "طرح نو",
        "علم",
        "علمی فرهنگی",
        "فاطمی",
        "فرهنگ معاصر",
        "قطره",
        "ققنوس",
        "کارگاه فیلم و گرافیک سپاس",
        "کتاب سرای نیک",
        "لاهیجی",
        "ماهی",
        "مثلث",
        "مرکز",
        "معین",
        "میم",
        "نگاه",
        "نگاه معاصر",
        "نوشته",
        "نی",
        "نیک",
        "نیکا",
        "یساولی",
      ],
  
      authors: [
        "همه",
        "آلیس دیویدسون",
        "ابراهیم پور داوود",
        "اریک کامرلینک",
        "اسکات لش",
        "امام خمینی",
        "ایبن الکساندر",
        "بهرام الهی",
        "تام سورل",
        "جومپا لاهیری",
        "حسین پیرنیا",
        "حسینعلی رحمتی",
        "حکیم نظامی گنجوی",
        "خواجه شمس‌الدین محمد حافظ شیرازی",
        "رابرت سوارت وود",
        "رنیت ناملا کین",
        "ریچارد کارلسون",
        "ریچارد کریستال",
        "زهره زاهدی",
        "ژان پی یر ویل",
        "سید نادرشاه حسینی کیانی",
        "عبدالحسین نوایی",
        "عبداللطیف طسوجی تبریزی",
        "عبید زاکانی",
        "علی اوجبی",
        "عمر خیام نیشابوری",
        "محمد اصغری",
        "محمد تقی لسان الملک سپهر",
        "محمد رادمنش",
        "محمود دانایی",
        "مصلح بن عبدالله سعدی شیرازی",
        "مولانا جلال الدین محمد بلخی",
        "مهدی اخوان ثالث",
        "مهندس الهام آخرتی",
        "مینو بدیعی",
        "ناصر حسینی مهر",
        "نیل دونالد والش",
        "ویلیام بلوم",
        "هاروکی موراکامی",
      ],
  
      translators: [
        "همه",
        "اصغر نوری امام زاده ای",
        "امیر حسین میرزائیان",
        "امیر مهدی حقیقت",
        "امین اصلانی",
        "ایمان گنجی",
        "باجلان فرخی",
        "بیژن افتخارجواهری",
        "پرویز شریفی درآمدی",
        "جمشید کیان فر",
        "جمعی از مترجمان",
        "حسام اتابک",
        "حسین بنی احمد",
        "حسین محی الدین الهی قمشه ای",
        "حسین معصومی همدانی",
        "دکتر نظام الدین نوری",
        "رسول یونان",
        "رضا مرادی اسپیلی",
        "سعید زاشکانی",
        "سعیده ایرانی",
        "سهیل سمی",
        "سیاوش کیان",
        "شاپور بهیان",
        "شهیندخت رئیس زاده",
        "عبد الحسین نیک گهر",
        "علی اصغر حلبی",
        "علی کیهان",
        "فروزان تجویدی",
        "فرهاد بدری زاده",
        "محمد جواد رنجکش",
        "محمود دانایی",
        "مسعود لعلی",
        "مسعود میرشاهی",
        "مظاهر مصفا",
        "منوچهر بیگدلی خمسه",
        "منوچهر شادان",
        "موژان غفاری",
        "مهدی غبرایی",
        "مهدی فلاح",
        "مهرداد وحدتی دانشمند",
        "ناهید رشید",
      ],
    },
  
    stationery: {
      type : "لوازم التحریر" ,
      products: [
        {
          id: 35,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-1.jpg",
          publisher: "پرتقال",
        },
        {
          id: 36,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-2.jpg",
          publisher: "نقش تندیس آریا",
        },
        {
          id: 37,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-3.jpg",
          publisher: "اسکول فنس",
        },
        {
          id: 38,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-4.jpg",
          publisher: "نورگیتی",
        },
        {
          id: 39,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-5.jpg",
          publisher: "پارسیکار",
        },
        {
          id: 40,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-6.jpg",
          publisher: "جوهر",
        },
        {
          id: 41,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-7.jpg",
          publisher: "مپد",
        },
        {
          id: 42,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-8.jpg",
          publisher: "نقش تندیس آریا",
        },
        {
          id: 43,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-9.jpg",
          publisher: "متفرقه",
        },
        {
          id: 44,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-10.jpg",
          publisher: "بیک",
        },
        {
          id: 45,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-11.jpg",
          publisher: "گاج",
        },
        {
          id: 46,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-12.jpg",
          publisher: "خرد",
        },
        {
          id: 47,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-13.jpg",
          publisher: "جوهر",
        },
        {
          id: 48,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-14.jpg",
          publisher: "جوهر",
        },
        {
          id: 49,
          category: "stationery",
          title: "  نشان کتاب بافتنی رنگی",
          price: "45000",
          cover: "./pictures/stationery-15.jpg",
          publisher: "جوهر",
        },
        {
          id: 50,
          category: "stationery",
          title: "نشان کتاب گچی",
          price: "55000",
          cover: "./pictures/stationery-16.jpg",
          publisher: "جوهر",
        },
      ],
      categories: [
        "همه",
        " لوازم هنری - گواش",
        " نوجوان - داستان نوجوان",
        " نوشت افزار - اتود",
        " نوشت افزار - اسلایم",
        " نوشت افزار - اکلیل و پولک",
        " نوشت افزار - پاک کن",
        " نوشت افزار - پرگار",
        " نوشت افزار - پست ایت",
        " نوشت افزار - تراش",
        " نوشت افزار - جامدادی",
        " نوشت افزار - جلد چسبی",
        " نوشت افزار - چسب",
        " نوشت افزار - چسب ماتیکی",
        " نوشت افزار - چوب بستنی",
        " نوشت افزار - خط کش و لوازم هندسی",
        " نوشت افزار - خمیر بازی",
        " نوشت افزار - خودکار",
        " نوشت افزار - خودنویس",
        " نوشت افزار - روان نویس",
        " نوشت افزار - ست تحریر",
        " نوشت افزار - ظرف غذا",
        " نوشت افزار - غلط گیر",
        " نوشت افزار - قمقمه و فلاسک",
        " نوشت افزار - قیچی",
        " نوشت افزار - کارت پستال",
        " نوشت افزار - کره جغرافیا",
        " نوشت افزار - گچ",
        " نوشت افزار - گواش",
        " نوشت افزار - ماژیک معمولی",
        " نوشت افزار - ماژیک وایت برد",
        " نوشت افزار - مداد",
        " نوشت افزار - نشان کتاب",
        " نوشت افزار - نوشت افزار",
      ],
      publishers: [
        "همه",
        " آوای باران",
        " آوند دانش",
        " آوین",
        " اس ام اس",
        " اس دی آی",
        " استدلر",
        " استورم",
        " الین",
        " اندیشه کهن",
        " ایگل",
        " برگ نو",
        " پارت",
        " پالمو",
        " پرتقال",
        " پلیکان",
        " جوهر",
        " جیحون",
        " حوض نقره",
        " خانه فرهنگ و هنر گویا",
        " دوران",
        " دیبایه",
        " دیدار",
        " رهنما",
        " زینگو",
        " سرزمین اهورایی",
        " شمشاد",
        " صدف",
        " فابرکاستل",
        " فرهنگ و هنر",
        " فکتیس",
        " فنی ایران",
        " کتابستان معرفت",
      ],
      translators: ["همه", "حسین دانشفر"],
    },
    
    textBook: {
      type : "کمک درسی" ,
      products : [
        {
          id: 51,
          category: "text-book",
          title: " ساعت چنده تربچه  (3 تا 6 سال) (4507) ",
          price: "45000",
          cover: "./pictures/textbook-1.jpg",
          discount: 15 ,
          publisher: "خیلی سبز",
          author : " مرجان ده حقی " ,
          translator : ""
        },
        {
          id: 52,
          category: "text-book",
          title: " آموزش فیزیک با رویکرد پدیده محور  ",
          price: "36000",
          cover: "./pictures/textbook-2.jpg",
          discount: 15 ,
          publisher: "مدرسه",
          author : " جوکا کوتاماکی " ,
          translator : " روح الله خلیلی بروجنی "
        },
        {
          id: 53,
          category: "text-book",
          title: " دروس یار تابستانه چهارم ابتدایی (میعاد) ",
          price: "149000",
          cover: "./pictures/textbook-3.jpg",
          discount: 15 ,
          publisher: "عصر میعاد",
          author : " ملیحه آبادیان " ,
          translator : ""
        },
        {
          id: 54,
          category: "text-book",
          title: " دقت در آموزش گام به گام دیکته‌نویسی کلمه‌ها  ",
          price: "150000",
          cover: "./pictures/textbook-4.jpg",
          discount: 15 ,
          publisher: "نشر مدرسه",
          author : " عبدالرحمان صفارپور " ,
          translator : ""
        },
        {
          id: 55,
          category: "text-book",
          title: " روش ها و راهبردهای تقویت دقت وتوجه  ",
          price: "95000",
          cover: "./pictures/textbook-5.jpg",
          discount: 15 ,
          publisher: "مدرسه",
          author : " آزیتا محمود پور " ,
          translator : ""
        },
        {
          id: 56,
          category: "text-book",
          title: " جامپینگ شبیه ساز آزمون ورودی تیزهوشان ششم  ",
          price: "435000",
          cover: "./pictures/textbook-6.jpg",
          discount: 15 ,
          publisher: "نشر پویش",
          author : " جمعی از نویسندگان " ,
          translator : ""
        },
        {
          id: 57,
          category: "text-book",
          title: " هوش تخصصی ششم ابتدایی (فرزانگان) ",
          price: "357000",
          cover: "./pictures/textbook-7.jpg",
          discount: 15 ,
          publisher: "نشر گامی تا فرزانگان",
          author : " علی قصاب " ,
          translator : ""
        },
        {
          id: 58,
          category: "text-book",
          title: " فصل میوه چینی دوم دبستان  ",
          price: "188000",
          cover: "./pictures/textbook-8.jpg",
          discount: 15 ,
          publisher: "نشر صیانت",
          author : " معصومه نجیب " ,
          translator : ""
        },
        {
          id: 59,
          category: "text-book",
          title: " زنگ حل مسئله همگام با ریاضیات کانگورو(5) (فاطمی) ",
          price: "188000",
          cover: "./pictures/textbook-9.jpg",
          discount: 15 ,
          publisher: "نشر فاطمی",
          author : " جعفر اسدی گرما رودی " ,
          translator : ""
        },
        {
          id: 60,
          category: "text-book",
          title: " جامع پیش دبستانی کارپوچینو (8362) ",
          price: "188000",
          cover: "./pictures/textbook-10.jpg",
          discount: 15 ,
          publisher: "گاج",
          author : " زلیخا جوکار " ,
          translator : ""
        },
        {
          id: 61,
          category: "text-book",
          title: " ریاضی اول دبستان کار (258)",
          price: "99000",
          cover: "./pictures/textbook-11.jpg",
          discount: 10 ,
          publisher: "خیلی سبز",
          author : " فرشته عبدی " ,
          translator : ""
        },
        {
          id: 62,
          category: "text-book",
          title: " درمان اختلالات خواندن ",
          price: "221000",
          cover: "./pictures/textbook-12.jpg",
          discount: 20 ,
          publisher: "فراروان",
          author : " مصطفی تبریزی " ,
          translator : "  "
        },
        {
          id: 63,
          category: "text-book",
          title: " تاریخ معاصر ایران یازدهم فرمول بیست (8652)",
          price: "180000",
          cover: "./pictures/textbook-13.jpg",
          discount: 20 ,
          publisher: "گاج",
          author : " ملیحه گرجی " ,
          translator : ""
        },
        {
          id: 64,
          category: "text-book",
          title: " شبیه ساز امتحان نهایی دوازدهم ریاضی (4609)",
          price: "195000",
          cover: "./pictures/textbook-14.jpg",
          discount: 20 ,
          publisher: "خیلی سبز",
          author : " گروه مولفین خیلی سبز " ,
          translator : ""
        },
        {
          id: 65,
          category: "text-book",
          title: " زیست دوازدهم فرمول بیست (8577) ",
          price: "186000",
          cover: "./pictures/textbook-15.jpg",
          discount: 10 ,
          publisher: "نشر گاج",
          author : " حمیدرضا زارع " ,
          translator : ""
        },
        {
          id: 66,
          category: "text-book",
          title: " بانک نهایی فارسی 2 یازدهم (4584) " ,
          price: "220000",
          cover: "./pictures/textbook-16.jpg",
          discount: 20 ,
          publisher: "خیلی سبز",
          author : " رضا اسماعیلی " ,
          translator : ""
        },
      ] ,
      categories : [
        "همه" ,
        " روانشناسی - ذهن و روح" ,
        " سبک زندگی - سرگرمی" ,
        " علمی - ریاضیات" ,
        " علمی - شیمی" ,
        " علمی - فیزیک" ,
        " کتاب تقویت مهارت های انگلیسی - grammar دستور زبان و گرامر" ,
        " کسب و کار و تجارت - مالی و حسابداری" ,
        " کمک درسی - المپیاد" ,
        " کمک درسی - املای فارسی" ,
        " کمک درسی - پنجم دبستان" ,
        " کمک درسی - پیش دانشگاهی" ,
        " کمک درسی - پیش دبستانی" ,
        " کمک درسی - تاریخ" ,
        " کمک درسی - جغرافیا" ,
        " کمک درسی - دانشگاهی" ,
        " کمک درسی - دهم" ,
        " کمک درسی - ریاضی" ,
        " کمک درسی - زبان انگلیسی"
      ] ,
      publishers : [
        "همه" ,
        " آبرنگ" ,
        " آگه" ,
        " پازینه" ,
        " پخش موسیقی آریانا" ,
        " پژوهشکده مطالعات فرهنگی و اجتماعی" ,
        " پیدایش" ,
        " تالیف" ,
        " جویا مجد" ,
        " چاووش" ,
        " حفیظ" ,
        " خوارزمی" ,
        " خیلی سبز" ,
        " دانشگاه تبریز" ,
        " دلیل ما" ,
        " دنیای نو" 
      ] ,
      authors : [
        "همه" ,
        " ابراهیم شهبازی" ,
        " اشرف کریمی" , 
        " اکبر نیکبخت" ,
        " امیر فرهاد تراب احمدی" ,
        " ایرالوین" , 
        " بهرام سیاهکل رودی" ,
        " جمشید اسکندری" , 
        " جمعی از نویسندگان" ,
        " جیمز استوارت" , 
        " حسن انوری" , 
        " خسرو خبیری" ,
        "  داریوش صادقی " ,
      ] ,
      translators : [
        "همه" ,
        " آرزو احمدایی" ,
        " آمنه مالمیر" ,
        " احمد خواجه نصیر توسی" ,
        " ارشک حمیدی" , 
        " پرویز امینی" , 
        " پرویز شهریاری" ,
        " جمعی از مترجمان" , 
        " جواد سید اشرف" , 
        " حسین ابراهیم زاده قلزم" , 
        " حسین جوادی"
      ]
  

    },

    foreignBook: {
      type: "زبان خارجی" ,
      products : [
        {
          id: 67,
          category: "foreign-book",
          title: " No Longer Human دیگر انسان نیست ",
          price: "99000",
          cover: "./pictures/foreign-book-1.jpg",
          discount: 15 ,
          publisher: "معیار اندیشه",
          author : " اوسامو دازای " ,
          translator : ""
        },
        {
          id: 68,
          category: "foreign-book",
          title: " White Nights شب های روشن ",
          price: "72000",
          cover: "./pictures/foreign-book-2.jpg",
          discount: 15 ,
          publisher: "زبان ما",
          author : " فئودور داستایوفسکی " ,
          translator : ""
        },
        {
          id: 69,
          category: "foreign-book",
          title: " 504Absolutely Essential Words (ویراست ششم)(جنگل)",
          price: "145000",
          cover: "./pictures/foreign-book-3.jpg",
          discount: 20 ,
          publisher: " جنگل جاودانه",
          author : " ماری برمبرگ " ,
          translator : ""
        },
        {
          id: 70,
          category: "foreign-book",
          title: " The journey (پاندای بزرگ و اژدهای کوچک) ",
          price: "152000",
          cover: "./pictures/foreign-book-4.jpg",
          discount: 20 ,
          publisher: "معیار اندیشه",
          author : " جیمز نوربری " ,
          translator : ""
        },
        {
          id: 71,
          category: "foreign-book",
          title: " The Cat Who Taught Zen گربه ای که ذن یاد می داد (زبان ماا) ",
          price: "195000",
          cover: "./pictures/foreign-book-5.jpg",
          discount: 20 ,
          publisher: " زبان ما ",
          author : " جیمز نوربری " ,
          translator : ""
        },
        {
          id: 72,
          category: "foreign-book",
          title: " Dont Believe Everything You Think  ",
          price: "833000",
          cover: "./pictures/foreign-book-6.jpg",
          discount: 10 ,
          publisher: "معیار اندیشه",
          author : " جوزف نوین " ,
          translator : ""
        },
        {
          id: 73,
          category: "foreign-book",
          title: " Big Panda and Tiny Dragon  پاندای بزرگ و اژد های کوچک ",
          price: "200000",
          cover: "./pictures/foreign-book-7.jpg",
          discount: 20 ,
          publisher: "معیار اندیشه",
          author : " جیمز نوربری " ,
          translator : ""
        },
        {
          id: 74,
          category: "foreign-book",
          title: "  The Hobbit ارباب حلقه ها ",
          price: "85000",
          cover: "./pictures/foreign-book-8.jpg",
          discount: 10 ,
          publisher: "معیار اندیشه",
          author : " جی.آر.آر.تالکین " ,
          translator : ""
        },
        {
          id: 75,
          category: "foreign-book",
          title: "  Ramona Quimby Age 8 رامونای هشت ساله ",
          price: "89000",
          cover: "./pictures/foreign-book-9.jpg",
          discount: 10 ,
          publisher: "معیار اندیشه",
          author : " بورلی کلی یری " ,
          translator : ""
        },
        {
          id: 76,
          category: "foreign-book",
          title: " Ramona The Pest رامونای آتش پاره ",
          price: "92000",
          cover: "./pictures/foreign-book-10.jpg",
          discount: 10 ,
          publisher: "معیار اندیشه",
          author : " بورلی کلی یری " ,
          translator : ""
        },
        {
          id: 77,
          category: "foreign-book",
          title: "The Witches جادوگرها ",
          price: "105000",
          cover: "./pictures/foreign-book-11.jpg",
          discount: 10 ,
          publisher: "معیار اندیشه",
          author : " رولد دال " ,
          translator : ""
        },
        {
          id: 78,
          category: "foreign-book",
          title: "Charlie and the Great Glass Elevator چارلی و آسانسور شیشه ای ",
          price: "112000",
          cover: "./pictures/foreign-book-12.jpg",
          discount: 10 ,
          publisher: "معیار اندیشه",
          author : " رولد دال " ,
          translator : ""
        },
        {
          id: 79,
          category: "foreign-book",
          title: "The Sun and Her Flowers  خورشید و گل هایش ",
          price: "105000",
          cover: "./pictures/foreign-book-13.jpg",
          discount: 10 ,
          publisher: " زبان ما ",
          author : " روپی کائور " ,
          translator : ""
        },
        {
          id: 80,
          category: "foreign-book",
          title: "the life changing manga of tidying up: a magical story ",
          price: "165000",
          cover: "./pictures/foreign-book-14.jpg",
          discount: 10 ,
          publisher: " زبان ما ",
          author : " ماری کندو " ,
          translator : ""
        },
        {
          id: 81,
          category: "foreign-book",
          title: "twisted love عشق پیچیده ",
          price: "200000",
          cover: "./pictures/foreign-book-15.jpg",
          discount: 10 ,
          publisher: " زبان ما ",
          author : " آنا هوانگ " ,
          translator : ""
        },
        {
          id: 82,
          category: "foreign-book",
          title: "Tuesdays with Morrie سه شنبه ها با موری ",
          price: "135000",
          cover: "./pictures/foreign-book-16.jpg",
          discount: 10 ,
          publisher: " زبان ما ",
          author : " میچ آلبوم " ,
          translator : ""
        },
      ] ,
      categories : [
        "همه" ,
        " سایر زبان ها - زبان آلمانی" ,
        " سایر زبان ها - زبان اسپانیایی" , 
        " سایر زبان ها - زبان ایتالیایی" , 
        " سایر زبان ها - زبان تایلندی" , 
        " سایر زبان ها - زبان ترکی" , 
        " سایر زبان ها - زبان چینی" , 
        " سایر زبان ها - زبان روسی" ,
        " سایر زبان ها - زبان عربی" , 
        " سایر زبان ها - زبان فرانسوی" , 
        " سایر زبان ها - زبان هلندی" ,
        " سایر زبان ها - زبان هندی" ,
        " سایر زبان ها - سایر زبان ها" ,
        " فرهنگ لغت و فرهنگ ها - dictionary دیکشنری و فرهنگ لغت"
      ] ,
      publishers : [
        "همه" ,
        " 360درجه" , 
        " آبرنگ" , 
        " آذین نگار" , 
        " استاندارد" ,
        " اقبال" , 
        " امیرکبیر" ,
        " بامداد کتاب" ,
        " بهزاد" ,
        " پارمیس" , 
        " جنگل جاودانه" , 
        " دانیال دامون" , 
        " دفتر فرهنگ اسلامی" , 
        " دنیای نو" , 
        " روزبهان" , 
        " رهنما" , 
        " سخنکده"
      ] ,
      authors : [
        "همه" ,
        " آنتوان دو سنت اگزوپری" , 
        " ابراهیم نظری تیموری" , 
        " ابوالقاسم آوند" , 
        " اچ داگلاس براون" ,
        " احمد بی نظیر" ,
        " امیر علی راسترو" , 
        " ای اچ ایروین" ,
        " ایرج مثال آذر" ,
        " پیتر نیومارک" ,
        " ترادی ارنسن" , 
        " حسن اشرف الکتابی" , 
        " حسین پنبه چی"
      ]
    } ,

    childrenBook: {
      type: " کودک و نوجوان " ,
      products : [
        {
          id: 83,
          category: "children-book",
          title: " نخ نامرئی (خشتی)(پرتقال) ",
          price: "69000",
          cover: "./pictures/children-book-1.jpg",
          discount: 20 ,
          publisher: " پرتقال ",
          author : " پاتریک کارست " ,
          translator : " آناهیتا حضرتی "
        },
        {
          id: 84,
          category: "children-book",
          title: " خرگوش گوش داد (خشتی)(پرتقال)",
          price: "96000",
          cover: "./pictures/children-book-2.jpg",
          discount: 20 ,
          publisher: " پرتقال ",
          author : " کوری دورفلد " ,
          translator : " رضی هیرمندی "
        },
        {
          id: 85,
          category: "children-book",
          title: " درخت باش (رحلی)(پرتقال) ",
          price: "69000",
          cover: "./pictures/children-book-3.jpg",
          discount: 20 ,
          publisher: " پرتقال ",
          author : " ماریا جانفراری " ,
          translator : " رضی هیرمندی "
        },
        {
          id: 86,
          category: "children-book",
          title: " روش ها و راهبردهای تقویت دقت وتوجه  ",
          price: "95000",
          cover: "./pictures/children-book-4.jpg",
          discount: 15 ,
          publisher: " مدرسه ",
          author : " آزیتا محمود پور " ,
          translator : ""
        },
        {
          id: 87,
          category: "children-book",
          title: " چرخ جهان چگونه می چرخد  ",
          price: "198000",
          cover: "./pictures/children-book-5.jpg",
          discount: 10 ,
          publisher: " ترجمان علوم انسانی ",
          author : " واتسلاف اسمیل " ,
          translator : ""
        },
        {
          id: 88,
          category: "foreign-book",
          title: " فابل (1) ",
          price: "250000",
          cover: "./pictures/children-book-6.jpg",
          discount: 10 ,
          publisher: " کتاب مجازی",
          author : " آدریان یانگ " ,
          translator : " پگاه خدادی "
        },
        {
          id: 89,
          category: "children-book",
          title: " ویجر  ",
          price: "298000",
          cover: "./pictures/children-book-7.jpg",
          discount: 10 ,
          publisher: " ترجمان علوم انسانی ",
          author : " دیوید گرن " ,
          translator : " علیرضا شفیعی نسب "
        },
        {
          id: 90,
          category: "children-book",
          title: " دختری که ماه را نوشید (گالینگور)(پرتقال) ",
          price: "270000",
          cover: "./pictures/children-book-8.jpg",
          discount: 20 ,
          publisher: " پرتقال ",
          author : " کلی بارن هیل " ,
          translator : " فروغ منصور قناعی "
        },
        {
          id: 91,
          category: "children-book",
          title: " هر کودک یک آهنگ است (خشتی)(پرتقال) ",
          price: "59000",
          cover: "./pictures/children-book-9.jpg",
          discount: 20 ,
          publisher: " پرتقال ",
          author : " نیکولا دیویس " ,
          translator : " رضی هیرمندی "
        },
        {
          id: 92,
          category: "children-book",
          title: " فلسفه برای نوجوانان  ",
          price: "95000",
          cover: "../pictures/children-book-11.jpg",
          discount: 20 ,
          publisher: " مهرگان خرد ",
          author : " مارک لینسن مایر " ,
          translator : " ندا تسلیمیان "
        },
        {
          id: 93,
          category: "children-book",
          title: " فیل ماکارون (خشتی)(پرتقال) ",
          price: "139000",
          cover: "../pictures/children-book-10.jpg",
          discount: 20 ,
          publisher: " پرتقال ",
          author : " جیکوب کریمر " ,
          translator : " رضی هیرمندی "
        },
        {
          id: 94,
          category: "children-book",
          title: " آد و غول های یخی ",
          price: "90000",
          cover: "../pictures/children-book-12.jpg",
          discount: 10 ,
          publisher: " پریان ",
          author : " نیل گیمن " ,
          translator : " فرزاد فربد "
        },
        {
          id: 95,
          category: "children-book",
          title: " باد ها ",
          price: "95000",
          cover: "../pictures/children-book-13.jpg",
          discount: 10 ,
          publisher: " افق ",
          author : " ماریو بارگاس یوسا " ,
          translator : " مهدی سرائی "
        },
        {
          id: 96,
          category: "children-book",
          title: " رقابت کوهستانی  ",
          price: "220000",
          cover: "../pictures/children-book-14.jpg",
          discount: 10 ,
          publisher: " اطراف ",
          author : " ایرلیس هانتر " ,
          translator : " ملیکا خوش نژاد "
        },
        {
          id: 97,
          category: "children-book",
          title: " رهایش کن (خشتی)(پرتقال) ",
          price: "59000",
          cover: "../pictures/children-book-15.jpg",
          discount: 10 ,
          publisher: " پرتقال ",
          author : " مارک کولاجووانی " ,
          translator : " نسرین علی محمدی "
        },
        {
          id: 98,
          category: "children-book",
          title: " پاستیل های بنفش (گالینگور)(پرتقال) ",
          price: "240000",
          cover: "../pictures/children-book-16.jpg",
          discount: 10 ,
          publisher: " پرتقال ",
          author : " کاترین اپلگیت " ,
          translator : " آناهیتا حضرتی "
        },
      ] ,
      categories : [
        " همه" ,
        " ادبیات - داستان کوتاه ایرانی" ,
        " ادبیات - داستان کوتاه خارجی" , 
        " ادبیات - رمان خارجی" ,
        " ادبیات - متون کهن" , 
        " حقوقی - عمومی" , 
        " زندگی نامه و خاطره - سفرنامه" , 
        " سبک زندگی - بهداشت و سلامت" ,
        " سینما و تئاتر - نمایشنامه و فیلمنامه" , 
        " طنز - داستان طنز" ,
        " طنز - شعر طنز" , 
        " علمی - جانورشناسی",
        " علمی - جغرافیا و زمین شناسی" , 
        " علمی - زیست شناسی" , 
        " علمی - عمومی" , 
        " فرهنگ، مرجع و دایرة المعارف - فرهنگ عامه" , 
        " فرهنگ، مرجع و دایرة المعارف - فرهنگ و مرجع" ,
        " کتاب های عمومی انگلیسی - انگیزشی و روان شناسی" ,
        " کمک درسی - پیش دبستانی" , 
        " کمک درسی - تیزهوشان" , 
        " کمک درسی - ریاضی" , 
        " کمک درسی - علوم تجربی" , 
        " کمک درسی - عمومی" , 
        " کمک درسی - ویژه دبستان" ,
        " کودک 6 تا 12 سال - آموزشی" , 
        " کودک 6 تا 12 سال - داستان" ,
      ] ,
      publishers : [
        "همه" ,
        " آریا نوین" , 
        " آفرینگان" , 
        " آوای سورنا" , 
        " آهسته" , 
        " ابوعطا" , 
        " اطلاعات" , 
        " افق" , 
        " با فرزندان" , 
        " بهجت" , 
        " پرسمان" , 
        " پیک دبیران" ,
        " ترانه" , 
        " جیحون" , 
        " چشمه" , 
        " حوض نقره" , 
        " ذکر" , 
        " زعفران" ,
        " سیب" , 
        " شقایق" , 
        " صدای معاصر" , 
        " طلایی"
      ] ,
      authors : [
        "همه" ,
        " آر ال استاین" , 
        " آماندا انیل" , 
        " آنتوان دو سنت اگزوپری" , 
        " آندرو شارمن" , 
        " آنیتا گانری" , 
        " اسکار وایلد" ,
        " باربارا تیلور" , 
        " برندا وال پل" , 
        " بریژیت آویسون" , 
        " بلیندا وبر" ,
        " بئاتریکس پاتر" , 
        " جکی جاف" , 
        " جکی گف" , 
        " داوود غفارزادگان" , 
        " دبورا چنسلر" , 
        " رابرت ام .آبرامسون" , 
        " رزی گرین وود" , 
        " رضا نباتی" , 
        " رود تئودورو" ,
        " رویا خوئی" , 
        " ریچارد مید" , 
        " ریچارد واکر" , 
        " شان کالری" , 
        " عبدالجبار احمدی" 
      ] ,
      translators : [
        "همه" ,
        " آبتین گلکار" , 
        " امیر باغستانی" , 
        " امیر صالحی طالقانی" , 
        " پروانه دادبخش" , 
        " پروین علی پور" , 
        " جمیله فراهانی" , 
        " جواد ثابت نژاد" , 
        " حسن سالاری" , 
        " حسین فتاحی" , 
        " خجسته کیهان" , 
        " رویا خوئی" , 
        " زهرا فشاهی" ,
        " سارا فضل علیزاده" ,
        " سارا قدیانی" , 
        " سعیدا زندیان" , 
        " شادی دبیری" ,
        " شهرام رجب زاده" ,
        " شیوا دوستانی" ,
        " علی خزاعی فر" , 
        " غلامرضا امامی" , 
        " فرزانه مهری" , 
        " فرهاد فراهانی" , 
        " فریده مهدوی دامغانی" ,
        " قیصر سربازی"
      ]
      
    } ,

    culturalGoods : {
      type : "کالای فرهنگی" ,
      products : [
        {
          id: 99,
          category: "cultural-goods",
          title: " تابلو مولانا 13*18 سانتی متر ",
          price: "55000",
          cover: "./pictures/cultural-good-1.jpg",
          discount: '' ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 100,
          category: "cultural-goods",
          title: " تابلو دست یاری 18*13 سانتی متر ",
          price: "69000",
          cover: "./pictures/cultural-good-2.jpg",
          discount: 20 ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 101,
          category: "cultural-goods",
          title: " ماهنامه جان و تن (شماره 9 و 10)(رحلی) ",
          price: "30000",
          cover: "./pictures/cultural-good-.jpg",
          discount: 10 ,
          publisher: " بینش نو ",
          author : "نیما قربانی"
        } ,
        {
          id: 102,
          category: "cultural-goods",
          title: " مجله هوپا (شماره 13)(رحلی) ",
          price: "199000",
          cover: "./pictures/cultural-good-4.jpg",
          discount: "" ,
          publisher: " هوپا ",
          author : "جمعی از نویسندگان" ,
          translator : ""
        } ,
        {
          id: 103,
          category: "cultural-goods",
          title: " تابلو مولانا 20*30 سانتی متر ",
          price: "110000",
          cover: "./pictures/cultural-good-5.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 104,
          category: "cultural-goods",
          title: " تقویم جیبی کد C 07  سال 1403 ",
          price: "48000",
          cover: "./pictures/cultural-good-6.jpg",
          discount: "" ,
          publisher: " کاغذ سیاه ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 105,
          category: "cultural-goods",
          title: " تابلو مرد غمگین 20*15 سانتی متر ",
          price: "75000",
          cover: "./pictures/cultural-good-7.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 106,
          category: "cultural-goods",
          title: " تابلو اغما 20*15 سانتی متر ",
          price: "75000",
          cover: "./pictures/cultural-good-8.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 107,
          category: "cultural-goods",
          title: " تابلو ابر و ماه 30*20 سانتی متر ",
          price: "110000",
          cover: "./pictures/cultural-good-9.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 108,
          category: "cultural-goods",
          title: " تابلو غروب 30*20 سانتی متر ",
          price: "110000",
          cover: "./pictures/cultural-good-10.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 109,
          category: "cultural-goods",
          title: " تابلو نقاشی موج 20*15 سانتی متر ",
          price: "75000",
          cover: "./pictures/cultural-good-11.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 110,
          category: "cultural-goods",
          title: " تابلو پرواز پرنده ها 30*20 سانتی متر ",
          price: "110000",
          cover: "./pictures/cultural-good-12.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 111,
          category: "cultural-goods",
          title: " تابلو تک درخت 30*20 سانتی متر ",
          price: "110000",
          cover: "./pictures/cultural-good-13.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 112,
          category: "cultural-goods",
          title: "فصلنامه تاریخی ثانیه (18)(تابستان 1402)",
          price: "120000",
          cover: "./pictures/cultural-good-14.jpg",
          discount: 10 ,
          publisher: " هزار کرمان ",
          author : "لیلا لطفی"
        } ,
        {
          id: 113,
          category: "cultural-goods",
          title: " تابلو کشتی  13*18 سانتی متر ",
          price: "55000",
          cover: "./pictures/cultural-good-15.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } ,
        {
          id: 114,
          category: "cultural-goods",
          title: " تابلو زندگی ساده نیست 13*18 سانتی متر ",
          price: "55000",
          cover: "./pictures/cultural-good-16.jpg",
          discount: "" ,
          publisher: " معاصران ",
          author : "" ,
          translator : ""
        } 
      ] ,
      categories : [
        "همه" , 
        " ادبیات - مقاله" ,
        " تابلو - تابلو انگیزشی" , 
        " تابلو - تابلو انیمیشن" ,
        " تابلو - تابلو بازیگر و کارگردان ایران" ,
        " تابلو - تابلو بازیگر و کارگردان خارجی" ,
        " تابلو - تابلو تولد" , 
        " تابلو - تابلو حیوانات" , 
        " تابلو - تابلو دانشمند" , 
        " تابلو - تابلو روز مادر" ,
        " تابلو - تابلو شاعران" , 
        " تابلو - تابلو شعر" , 
        " تابلو - تابلو طبیعت، گل و منظره" , 
        " تابلو - تابلو عاشقانه" , 
        " تابلو - تابلو فانتزی" , 
        " تابلو - تابلو کودکانه" , 
        " تابلو - تابلو ماشین و موتور" , 
        " تابلو - تابلو مشاهیر" , 
        " تابلو - تابلو مکان های دیدنی" ,
        " تابلو - تابلو موسیقیدان، خواننده" , 
        " تابلو - تابلو نقاش، طراح" , 
        " تابلو - تابلو نقاشی" , 
        " تابلو - تابلو نویسندگان" , 
        " تابلو - تابلو ورزشکاران" , 
        " تابلو - تابلو هنری"  
      ] ,
      publishers : [
        "همه" ,
        " آبان" , 
        " آسمان شب" , 
        " اسم" , 
        " اطلاعات" , 
        " افق" , 
        " اقبال" , 
        " اندیشه احسان" , 
        " بان" , 
        " بهجت" , 
        " بینش نو" ,
        " بیهق" , 
        " پیام امروز" ,
        " جاودان خرد" , 
        " جیحون" , 
        " چشمه" , 
        " حوض نقره" , 
        " خیام" , 
        " دانوش" , 
        " دفتر فرهنگ اسلامی" , 
        " شقایق" , 
        " کتابستان معرفت" , 
        " گوی" , 
        " مجله آنگاه" , 
        " مرکز سیاووشان"
      ] ,
      authors : [
        "همه" , 
        " آرش  تنهایی" , 
        " آرش صادق بیگی" , 
        " آنتوان دو سنت اگزوپری" , 
        " اردشیر رستمی" ,
        " انوش صالحی" ,
        " حسین اسماعیلی" , 
        " حسین کاظم زاده ایرانشهر" ,
        " حسین مجتهدی" , 
        " داریوش معمار" ,
        " رابین وود" , 
        " رضا عابدینی" ,
        " رضاسرور" ,
        " روزبه فکری" , 
        " سارا نوری" , 
        " شهریار خانی زاده" , 
        " عاطفه خلفی" , 
        " علی حسینخانی" , 
        " علی میرزایی" , 
        " علیرضا آشتیانی" ,
        " علیمراد فدایی نیا" , 
        " فرهاد ناظر زاده كرمانی" 
      ] ,
      translators : [
        "همه" , 
        " دل آرا قهرمان"
      ]
    }
};




export { allProducts }  
   